# Generated by Django 3.2.16 on 2023-04-15 13:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('building', models.CharField(max_length=255, verbose_name='Здание')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('price', models.CharField(max_length=255, verbose_name='Начальная цена')),
                ('count_time_block', models.TimeField(default=datetime.time(0, 40), verbose_name='затрачиваемое время (лучше по 40 мин)')),
            ],
        ),
        migrations.CreateModel(
            name='Stylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.CharField(default='', max_length=255, verbose_name='Отчетсво')),
                ('photo', models.ImageField(upload_to='images/stylists/')),
                ('about', models.TextField(verbose_name='О себе')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('client_patronymic', models.CharField(default='', max_length=255, verbose_name='Отчество')),
                ('client_phone', models.CharField(max_length=13, verbose_name='Номер телефона')),
                ('appointment_reg_date', models.DateTimeField(auto_now_add=True)),
                ('appointment_beg_date', models.TimeField(verbose_name='Начало')),
                ('appointment_end_date', models.TimeField(verbose_name='Конец')),
                ('proof', models.BooleanField(default=False)),
                ('address', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='register.address', verbose_name='Адрес')),
                ('option', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='register.option', verbose_name='Услуга')),
                ('stylist', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='register.stylist', verbose_name='Стилист')),
            ],
        ),
    ]
