# Generated by Django 3.2.16 on 2023-04-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylist',
            name='photo',
            field=models.ImageField(default='null', null=True, upload_to='images/stylists/'),
        ),
    ]
