# Generated by Django 3.2.16 on 2023-04-15 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_stylist_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='title',
            field=models.CharField(default='Клаевала 4а', max_length=255, verbose_name='Отображаемый адрес'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.CharField(default='Запись от %d-%m-%Y (%H:%M)', max_length=255),
        ),
        migrations.AddField(
            model_name='option',
            name='title',
            field=models.CharField(default='Наименование от %d-%m-%Y (%H:%M)', max_length=255),
        ),
        migrations.AddField(
            model_name='stylist',
            name='title',
            field=models.CharField(default='ФИО', max_length=255, verbose_name='Отображаемое ФИО'),
        ),
        migrations.AlterField(
            model_name='option',
            name='count_time_block',
            field=models.TimeField(default=datetime.time(0, 40), verbose_name='Затрачиваемое время (лучше кратное 40 мин)'),
        ),
    ]
