# Generated by Django 3.2.16 on 2023-04-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20230415_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='title',
        ),
        migrations.RemoveField(
            model_name='option',
            name='title',
        ),
        migrations.RemoveField(
            model_name='stylist',
            name='title',
        ),
    ]
