# Generated by Django 3.2.16 on 2023-04-15 16:30

from django.db import migrations, models
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20230415_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='title',
            field=models.CharField(default=register.models.get_default_my_date, max_length=255),
        ),
    ]
