# Generated by Django 4.1.5 on 2023-03-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_path', models.ImageField(upload_to='images/%Y-%m/')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
